//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Reservation_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string username { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> train_id { get; set; }
        public Nullable<int> pnr_no { get; set; }
        public string train_name { get; set; }
        public Nullable<System.DateTime> travelling_date { get; set; }
        public Nullable<System.TimeSpan> arrival_time { get; set; }
        public Nullable<System.TimeSpan> departure_time { get; set; }
        public string trainClass { get; set; }
        public Nullable<double> total_price { get; set; }
        public Nullable<int> seat_no { get; set; }
        public string status { get; set; }
    
        public virtual Train Train { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
