//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Reservation_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainPrice
    {
        public int id { get; set; }
        public Nullable<int> train_id { get; set; }
        public string train_name { get; set; }
        public Nullable<double> first_class_price { get; set; }
        public Nullable<double> second_class_price { get; set; }
        public Nullable<double> sleeper_class_price { get; set; }
        public Nullable<int> first_class_tickets_available { get; set; }
        public Nullable<int> second_class_tickets_available { get; set; }
        public Nullable<int> sleeper_class_tickets_available { get; set; }
        public Nullable<int> total_available_tickets { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
